#!/bin/bash

# Vue 3 Migration - Quick Test Commands
# Run these to verify the migration

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  T.O.M.E. Vue 3 Migration - Phase 1 Testing                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

cd /Users/sbinder/Projects/tome/app

echo "📦 Step 1: Install dependencies..."
echo "Command: npm install"
echo ""
echo "This will:"
echo "  ✓ Install Vue 3.5"
echo "  ✓ Install Vue Router 4.3"
echo "  ✓ Install Vuex 4.1"
echo "  ✓ Install Vuetify 3.5"
echo "  ✓ Install TypeScript 5.3"
echo ""
echo "Expected time: 2-5 minutes"
echo "Run this when ready:"
echo ""
echo "  npm install"
echo ""
echo "---"
echo ""

echo "🚀 Step 2: Test development server..."
echo "Command: npm run serve"
echo ""
echo "Expected output:"
echo "  ✓ Compiles without errors (or only in other components)"
echo "  ✓ Starts dev server at http://localhost:8080"
echo "  ✓ Login page accessible at /#/login"
echo "  ✓ Navigation bar renders"
echo ""
echo "Common issues and how to fix them:"
echo ""
echo "Issue: 'Cannot find module @/axios'"
echo "  → Make sure src/axios/index.js exists"
echo ""
echo "Issue: 'Vuetify is not defined'"
echo "  → Check src/plugins/vuetify.js exports correctly"
echo ""
echo "Issue: 'Cannot find router'"
echo "  → Check src/router/index.js exports router"
echo ""
echo "---"
echo ""

echo "✅ Step 3: Verify components work"
echo ""
echo "Navigate to: http://localhost:8080/#/login"
echo ""
echo "Check these:"
echo "  ✓ Page loads without errors"
echo "  ✓ Navigation menu appears (hamburger icon)"
echo "  ✓ T.O.M.E. title visible"
echo "  ✓ Login form renders with email/password fields"
echo "  ✓ No console errors (F12 to check)"
echo ""

echo "---"
echo ""
echo "🎯 Summary of Migration:"
echo ""
echo "Files Updated (13):"
echo "  ✓ package.json - Vue 3 dependencies"
echo "  ✓ tsconfig.json - TypeScript 5 config"
echo "  ✓ src/main.ts - Entry point migrated"
echo "  ✓ src/router/index.js - Vue Router 4"
echo "  ✓ src/store/index.ts - Vuex 4"
echo "  ✓ src/plugins/vuetify.js - Vuetify 3"
echo "  ✓ src/App.vue - Root component"
echo "  ✓ src/pages/LoginPage.vue - Auth page"
echo "  ✓ src/components/TomeNavigation.vue - Navigation"
echo "  ✓ src/components/ProfileImage.vue - Avatar"
echo "  ✓ src/components/SnackbarStore.vue - Notifications"
echo "  ✓ src/components/LogoutComponent.vue - Logout"
echo "  ✓ src/axios/index.js - HTTP client"
echo ""
echo "Status: Framework setup complete ✅"
echo "         3 critical components migrated ✅"
echo "         Ready for testing 🚀"
echo ""
echo "---"
echo ""
echo "⚠️  Next Phase (after this works):"
echo ""
echo "After confirming the 3 components work, the next phase is to:"
echo "  1. Migrate remaining ~40 components"
echo "  2. Fix component-specific errors"
echo "  3. Test full app flow"
echo "  4. Deploy to staging"
echo ""
echo "═════════════════════════════════════════════════════════════════"
